### ISSUE TITLE
Can't use at all.

### ISSUE THREAD

**Issue by jkbbwr** [AsynkronIT/gam#14]
Install process is entirely broken.
go version
`go version go1.6.3 linux/amd64`
protoc version
`libprotoc 3.0.0`

Your library cannot be installed with `go get` and trying to build it by hand yields the following error 
```
cd actor/; protoc --gofast_out=plugins=grpc:. --proto_path=. --proto_path=/home/jakob/projects/other/lib/src ./*.proto
go build ./...
# github.com/rogeralsing/gam/remoting/messages
remoting/messages/protos.pb.go:93: undefined: grpc.SupportPackageIsVersion2
make: *** [Makefile:7: build] Error 2
```

**Comment by rogeralsing** [comment]
The error message indicates that you have an outdated version of protoc protobuf compiler installed.
Maybe you have it in $path at some other location?

**Comment by rogeralsing** [comment]
You state that you have protoc 3, check your protobuf go libs too, something is not what it should in the proto code.

**Comment by nullbus** [comment]
I had same issue and solved by go-get'ing `github.com/rogeralsing/gam`, not `github.com/AsynkronIT/gam`.

Github redirects `github.com/rogeralsing/gam` to this repo but it seems that go tool cannot handle this redirection.

**Comment by rogeralsing** [comment]
oh. I will update the sources. I moved the code over here to my company repo a few days ago.

**Comment by nullbus** [comment]
I see. Thank you for quick response :)

**Comment by rogeralsing** [comment]
Repo has been updated with the correct paths. closing
