### ISSUE TITLE
Find the Self *PID

### ISSUE THREAD

**Issue by mvbaffa** [AsynkronIT/gam#15]
Sorry,

But I could not find how to get the current actor pid. I have tried with actor.Context.Self():
`pid := actor.Context.Self()`

but I got the error:

> not enough arguments in call to method expression actor.Context.Self

But the definition of actor.Context.Self defines that it wll return *PID.

Can you help me

**Comment by rogeralsing** [comment]
I found the problem.
You are using `actor.Context.Self()` which is the fully qualified type. the argument you have access to is 
`context`, so `context.Self()` is what you want.

**Comment by mvbaffa** [comment]
It worked, Thanks
