### ISSUE TITLE
Pipe Self Message

### ISSUE THREAD

**Issue by mvbaffa** [AsynkronIT/gam#17]
Is there a Pipe method so that an actor can send messages for itself.

If I send a message to the actor from a goroutine or from another actor it works, but if I want to send a message from itself the message does not arrive.

Thanks

**Comment by rogeralsing** [comment]
`context.Self().Tell(message)` should do it.
One thing that can make it look weird is if you pass the message by value but receive as a reference or vice versa. That would be my guess.

Can you show an example of your code?

**Comment by rogeralsing** [comment]
The API have now been extended with `Ask` and `PipeTo`

```go
someActor.Ask(msg).PipeTo(context.Self())
```
