### ISSUE TITLE
Distributed Publish Subscribe support?

### ISSUE THREAD

**Issue by yi719** [AsynkronIT/gam#18]
hi, 

I'm a newbie in Golang, trying to build a chat service with gam,

just wonder if is there something similar to [Distributed Publish Subscribe in Akka](http://doc.akka.io/docs/akka/2.4.11/scala/distributed-pub-sub.html)

**Comment by rogeralsing** [comment]
There is no Cluster support (yet) but take a look at https://github.com/AsynkronIT/gam/tree/dev/examples/chat

This will allow you to connect clients to a server and then have the server send data to all its clients.
Is this enough for your usecase`?

**Comment by yi719** [comment]
thx rogeralsing, 

I think it's enough for our usecase
