### ISSUE TITLE
Disconnected remote actor causes fatal error on tell

### ISSUE THREAD

**Issue by MechWipf** [AsynkronIT/gam#36]
I am using your package to write a little chat program similar to your example.

Now, when one of the clients disconnects from the server (simple exit or crash) and the server tries to send something to the disconnected client the `endpointWriter` throws a fatal error which cannot be catched.

Did I miss something in `remoting` to manage errors or checking if an remote actor got disconnected?

**Comment by rogeralsing** [comment]
This was the result of some `log.Fatal` calls, they have been replaced with proper error handling.
The fix is available now.
I should probably make any sends to a dead node go to `DeadLetter` also
